//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace game_reviews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int ID { get; set; }
        public int ID_Game { get; set; }
        public int ID_User { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Users Users { get; set; }
    }
}
